### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by 3dgoose** [theabbie/meme-api#2]
Please, describe exactly how to download the api.

**Comment by theabbie** [comment]
@CosmosRGB Apologies, this is an incomplete (empty) project right now and can't be used, I am planning to work on it in future.

**Comment by 3dgoose** [comment]
Thx because it won't work.

**Comment by 3dgoose** [comment]
> @CosmosRGB Apologies, this is an incomplete (empty) project right now and can't be used, I am planning to work on it in future.

Can I help you code it?

**Comment by theabbie** [comment]
@CosmosRGB Sure, if you want to, but if building from scratch you could also build your own seperate project.
